version: '3'
services: 
  # Spring Boot Application
  spring-boot-app:
    image: web-backend
    ports:
      - 0.0.0.0:8092:8091
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/demo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql
  front-angular-app:
    image: web-front
    ports:
      - 0.0.0.0:3000:4200
    depends_on:
      - spring-boot-app
    
  # MySQL Database
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 0.0.0.0:3309:3306
    volumes:
      - demo:/var/lib/mysql
  # liste des volumes
volumes:
  demo:
